### ISSUE TITLE
<RDF:rdf> closed too soon

### ISSUE THREAD

**Issue by teskenazi** [griwodz/ladioproject#12]
https://github.com/griwodz/ladioproject/blob/d1f5a005f4d74e94b5cfb1633fe98cd17b3926ed/ontologies/ladio/ladio.rdf#L15

the '>' of RDF:rdf is closing one term too soon, "xml:base="http://ladioprojects.eu/ontologies/ladio">" is excluded of it

**Comment by griwodz** [comment]
fixed
