### ISSUE TITLE
forbidden use of rdf:resource

### ISSUE THREAD

**Issue by teskenazi** [griwodz/ladioproject#13]
https://github.com/griwodz/ladioproject/blob/d1f5a005f4d74e94b5cfb1633fe98cd17b3926ed/ontologies/ladio/ladio.rdf#L126

You cannot use a rdf:resource inside a owl:unionof

I suggest to declare multiple domains directly in the the Property level wimply like this :+1: 
<rdfs:Property rdf:ID="hasParent">
     ....
    <rdfs:domain rdf:resource="#Shot"/>
    <rdfs:domain rdf:resource="#Take"/>
    <rdfs:domain rdf:resource="#VirtualScene"/>

**Comment by griwodz** [comment]
Unexpected, since I saw the owf:unionof in examples. Fixed.

**Comment by griwodz** [comment]
fixed
